import iconGenerator from 'utils/iconGenerator';
import BellSvg from 'assets/icons/bell.svg';
import UserSvg from 'assets/icons/user.svg';
import RightArrowSvg from 'assets/icons/arrow-right.svg';
import LeftArrowSvg from 'assets/icons/arrow-left.svg';
import EllipseSvg from 'assets/icons/ellipse.svg';
import LogoSvg from 'assets/icons/logo.svg';
import HomeSvg from 'assets/icons/home.svg';
import StarFillSvg from 'assets/icons/star-fill.svg';
import StarEmptySvg from 'assets/icons/star-empty.svg';
import WifiSvg from 'assets/icons/wifi.svg';
import CameraSvg from 'assets/icons/camera.svg';
import WhiteCameraSvg from 'assets/icons/camera-white.svg';
import OrangeCameraSvg from 'assets/icons/camera-orange.svg';
import MicSvg from 'assets/icons/mic.svg';
import FileSvg from 'assets/icons/file.svg';
import OrangeMicSvg from 'assets/icons/mic-orange.svg';
import ViewsSvg from 'assets/icons/views.svg';
import CartSvg from 'assets/icons/cart.svg';
import OvalSvg from 'assets/icons/oval.svg';
import ActiveUserSvg from 'assets/icons/user-active.svg';
import InactiveUserSvg from 'assets/icons/user-inactive.svg';
import FacebookSvg from 'assets/icons/facebook.svg';
import TwitterSvg from 'assets/icons/twitter.svg';
import InstagramSvg from 'assets/icons/instagram.svg';
import HamburgerSvg from 'assets/icons/hamburger.svg';

export const Bell = iconGenerator(BellSvg);
export const User = iconGenerator(UserSvg);
export const RightArrow = iconGenerator(RightArrowSvg);
export const LeftArrow = iconGenerator(LeftArrowSvg);
export const Ellipse = iconGenerator(EllipseSvg);
export const Logo = iconGenerator(LogoSvg);
export const Home = iconGenerator(HomeSvg);
export const StarFill = iconGenerator(StarFillSvg);
export const StarEmpty = iconGenerator(StarEmptySvg);
export const Wifi = iconGenerator(WifiSvg);
export const WhiteCamera = iconGenerator(WhiteCameraSvg);
export const OrangeCamera = iconGenerator(OrangeCameraSvg);
export const Camera = iconGenerator(CameraSvg);
export const Mic = iconGenerator(MicSvg);
export const File = iconGenerator(FileSvg);
export const OrangeMic = iconGenerator(OrangeMicSvg);
export const Views = iconGenerator(ViewsSvg);
export const Cart = iconGenerator(CartSvg);
export const Oval = iconGenerator(OvalSvg);
export const ActiveUser = iconGenerator(ActiveUserSvg);
export const InActiveUser = iconGenerator(InactiveUserSvg);
export const Facebook = iconGenerator(FacebookSvg);
export const Twitter = iconGenerator(TwitterSvg);
export const Instagram = iconGenerator(InstagramSvg);
export const Hamburger = iconGenerator(HamburgerSvg);
